session_name: access-servers
windows:
- window_name: dev
  layout: tiled
  shell_command_before:
    - cd ~/devel/sosr2019-dsfc # run as a first command in all panes
  panes:
    - echo hi           
    - echo hi
    - shell_command:
        - sleep 2
        - vagrant ssh sfc1
    - shell_command:
        - sleep 3
        - vagrant ssh sfc1
    - shell_command:
        - sleep 4
        - vagrant ssh sfc2
    - shell_command:
        - sleep 5
        - vagrant ssh sfc2
    # - shell_command:
    #    - sleep 6
    #    - vagrant ssh sfc3
    # - shell_command:
    #    - sleep 7
    #    - vagrant ssh sfc3
