---
- name: Provision environment to play with BPF
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        update_cache: yes # Run 'apt update' before install
      loop:
        - make
        - gcc
        - g++
        - pkg-config
        - libssl-dev
        - bc
        - libelf-dev
        - libpcap-dev
        - gcc-multilib
        - libncurses5-dev
        - git
        - graphviz
        - llvm
        - clang
        - elfutils
        - libmnl-dev
        - bison
        - flex
        - ifupdown
        - python-netifaces
        - binutils-dev
        - hping3
        - net-tools
        - autoconf
        - automake
        - libtool
        - unzip
        - curl
        - protobuf-compiler
        - protobuf-c-compiler
        - libprotobuf-c-dev
        - vim
        - python-protobuf
      tags: install
    - name: Clone prototype-kernel project
      git:
        repo: https://github.com/netoptimizer/prototype-kernel.git
        dest: /home/ebpf/prototype-kernel
      ignore_errors: yes
      tags: clone
    - name: Clone linux kernel net-next tree
      git:
        repo: https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
        dest: /home/ebpf/net-next
        version: v5.0
        depth: 1 # Reduce commit history to download faster
      ignore_errors: yes
      tags: clone
    - name: Install bpftool
      shell: make && make install
      args:
        chdir: /home/ebpf/net-next/tools/bpf/bpftool
      ignore_errors: yes
      tags: kernel